いいね機能の実装
keisukesaito7/tenkue-board-r009 pull request #11
Opened 2020-11-20 12:48 UTC by keisukesaito7

## 何か

### 1. ログインすると、投稿一覧ページ、投稿詳細ページでいいねをできる

[![Image from Gyazo](https://i.gyazo.com/4fdffa196cf9bb8a29fcfd051bc678a0.gif)](https://gyazo.com/4fdffa196cf9bb8a29fcfd051bc678a0)

### 2. いいねの表示はユーザーごとに変わる＆いいねが0のときはカウントを表示しない

[![Image from Gyazo](https://i.gyazo.com/38939aeb76e62ac85891353ead6f008f.gif)](https://gyazo.com/38939aeb76e62ac85891353ead6f008f)

### 3. ログアウト時にいいねしようとすると、ログインページに飛ばされる

[![Image from Gyazo](https://i.gyazo.com/f21210f6252d6a0372237f29b26caa02.gif)](https://gyazo.com/f21210f6252d6a0372237f29b26caa02)

## 追加・変更

* モデル
  * like.rb
  * user.rb
  * post.rb
* マイグレーション
  * likes_tableのマイグレーションファイル
* コントローラ
  * likes_controller.rb
* ビュー（いいねリンクを実装）
  * posts/index.html.erb
  * posts/show.html.erb
  * likes/_like.html.erb
* その他
  * rails g model で作成されたファイル
  * rails db:migrate で作成されたファイル
  * rails g controller likes で作成されたファイル

2020-11-20 13:01 UTC, keisukesaito7 commented on config/routes.rb
> +  delete 'posts/:post_id/likes', to: 'likes#destroy', as: 'post_like'
【補足（いい方法があれば教えて下さい。現状、動作には問題ありません）】
本当は``resources :posts, except: :index do ~ end``にネストをして書いたほうがいいとはわかっているんですが、その場合、destroyアクションのURI末尾に``/:id``が付いてしまいます。

自分自身、``ログインユーザー、各投稿に紐づくいいねのidを取得する方法``が思いつかなかったので、``このようにURIから/:idが外れる形``でルーティングを設定しました。

2020-11-21 03:44 UTC, ikemomo reviewed
2点コメントしました。確認お願いしますー！

2020-11-21 03:44 UTC, ikemomo commented on app/controllers/likes_controller.rb
> +  end
createアクションとdestroyアクション共に、`post_id: params[:post_id]`が共通なので、

```
private
def set_post
  @post = Post.find(params[:post_id])
end
```

`set_post`でまとめて、`post_id: @post.id`にすると良いと思いました。
理由は、posts_controller.rbの方でもset_postで共通化しているから、さらに見やすいコードになると思うからです！

2020-11-21 03:44 UTC, ikemomo commented on config/routes.rb
> +  delete 'posts/:post_id/likes', to: 'likes#destroy', as: 'post_like'
色々と参考記事を見てみましたが、destroyに:idがついても問題ないように思ったので、個人的にはネストさせても良いと考えます！ちなみに、転クエのサンプル掲示板はどうなっているのか見てみましたが、destroyアクションのURI末尾に`/:id`付いているままでした！

2020-11-21 09:44 UTC, keisukesaito7 commented on app/controllers/likes_controller.rb
> +  end
確かにそうですね、ご指摘ありがとうございます！
こちらは対応しました！

2020-11-21 10:05 UTC, aoi1019 commented
実装お疲れ様です！
すみません、確認が遅れました！LGTMですー！

routeの件ですが、ネストを使う方でいいかと思います〜🙋‍♂️

2020-11-21 13:42 UTC, ikemomo commented
確認しました！LGTMです！

2020-11-22 02:44 UTC, sew-sou19 requested changes
ほぼOKです！
一部だけ修正お願いしますー！

2020-11-22 02:44 UTC, sew-sou19 commented on app/assets/javascripts/likes.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
不要なファイルは削除するようにしましょうー！（混乱を避けるため）

2020-11-22 02:44 UTC, sew-sou19 commented on app/assets/stylesheets/likes.scss
> +// Place all the styles related to the likes controller here.
こちらの不要なファイルも削除するようにしましょうー！（混乱を避けるため）

2020-11-22 02:55 UTC, keisukesaito7 commented
レビューありがとうございます！
不要なファイルを削除するという観点は今までなかったので、勉強になります！

2020-11-22 03:07 UTC, sew-sou19 approved these changes
LGTMです！

2020-11-22 04:49 UTC, merged