掲示板編集/削除機能
keisukesaito7/tenkue-board-r009 pull request #12
Opened 2020-11-21 14:07 UTC by aoi1019

# What
### 1.編集機能を実装
[![Image from Gyazo](https://i.gyazo.com/a123d7fc737db6cd7c65210f86603a47.gif)](https://gyazo.com/a123d7fc737db6cd7c65210f86603a47)

### 2. 削除機能&確認表示を実装
[![Image from Gyazo](https://i.gyazo.com/b7974622167d5a7b69308789fdb025b4.gif)](https://gyazo.com/b7974622167d5a7b69308789fdb025b4)

### 3. 投稿者だけが編集ページに遷移できる
[![Image from Gyazo](https://i.gyazo.com/9808090955c60c72a5a0fd5b609b3a59.gif)](https://gyazo.com/9808090955c60c72a5a0fd5b609b3a59)

### 4.投稿内容が空だと編集できない
[![Image from Gyazo](https://i.gyazo.com/3ce8916784b97e059460e3bb8eaa36c4.gif)](https://gyazo.com/3ce8916784b97e059460e3bb8eaa36c4)

2020-11-21 23:58 UTC, keisukesaito7 reviewed
お疲れさまです！
基本的には問題ありませんが、レイアウトの部分で１つ気になった点がありました。
ご確認をよろしくお願いします！

2020-11-21 23:58 UTC, keisukesaito7 commented on app/views/posts/edit.html.erb
> +        <div class="form_area">
【エラーメッセージの場所について】
新規投稿のときに気づきませんでしたが、``<div class="form_area">``の中にエラーメッセージを入れた方が、よりサンプル掲示板に近づきますし、フォームとメッセージの横幅も合ってレイアウト的にきれいだなと思いました！
なので、posts/index.html.erb と posts/edit.html.erb のエラーメッセージを、``<div class="form_area">``の中に入れるのはどうでしょうか？ 実装して確認してみて下さい！
[![Image from Gyazo](https://i.gyazo.com/1b7843fd6ad2af374d2b79a89c3ceb5b.png)](https://gyazo.com/1b7843fd6ad2af374d2b79a89c3ceb5b)

2020-11-22 02:37 UTC, ikemomo reviewed
1点コメントしました。確認お願いします！
また投稿一覧のプルリクを出したときには気づけなかったのですが、`post.rb`のコードを見ていた時に、ユーサーが削除された場合にそこに紐づいてる投稿が一緒に削除されるように設定されていないのかな？と思いました。`dependent: :delete_all`などを付ける必要があるかと思います。こちらも併せて確認お願いします！

2020-11-22 02:37 UTC, ikemomo commented on app/controllers/posts_controller.rb
> +      render :edit
createアクションのところでは`render 'posts/new'`という書き方になっているけど、editアクションでは`render :edit`という書き方になっているところが少し気になりました！この場合、createアクションを` render :new`にするか、updateアクションを`render: 'posts/edit'`にするかどちらかに統一させた方が良いのかなと思いました。

2020-11-22 02:55 UTC, aoi1019 commented on app/controllers/posts_controller.rb
> +      render :edit
たしかにおっしゃる通りです！
修正しますー！

また`dependent: :delete_all`というのは初耳だったので調べてみたのですが、
今回は`dependent: :destroy`の方が良いかな？？と思ったのでこちらを使いたいと思います！！

参考資料
https://qiita.com/kobukurosirokuma/items/b86ac6b620d2b15c0164

2020-11-22 03:03 UTC, keisukesaito7 commented on app/views/posts/edit.html.erb
> +        <div class="form_area">
確認しました！
ありがとうございます！

2020-11-22 03:29 UTC, keisukesaito7 reviewed
LGTMです。
流れ的に、こちらのブランチのマージの後に、いいね機能のブランチをマージします。

2020-11-22 03:29 UTC, keisukesaito7 commented on app/models/user.rb
> +  has_many :posts, dependent: :destroy
もしユーザー削除を想定するのであれば、ここはむしろ``dependent: :destroy``でないといけないので、この書き方でOKだと思います！
（補足）
``delete_all``にすると、いいね&コメントが削除できていない状態で、投稿を一括で削除しようとするので、いいね＆コメント側の``foreign_key制約``に引っかかって削除できない例外が発生するからです。

2020-11-22 03:32 UTC, ikemomo commented on app/models/user.rb
> +  has_many :posts, dependent: :destroy
あおいさん修正ありがとうございますー！
さいとうさん、アドバイスありがとうございます！勉強になりました！

2020-11-22 03:33 UTC, ikemomo commented
修正確認しました！LGTMですー！

2020-11-22 06:53 UTC, sew-sou19 requested changes
大枠は問題ないですー！
一部修正をお願いします！

2020-11-22 06:53 UTC, sew-sou19 commented on app/views/posts/new.html.erb
>        <%# フォームを設置 %>
不要な記述は削除しましょう！

2020-11-22 06:53 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    unless current_user.id == @post.user_id
unless文は、実行するコードが1行なら後置で記述してあげたほうが読みやすいです。
```suggestion
    redirect_to root_path unless current_user.id == @post.user_id
```

2020-11-22 12:01 UTC, sew-sou19 requested changes
ごめんなさい、1点だけ追加で修正をお願いします！！

2020-11-22 12:01 UTC, sew-sou19 commented on app/views/posts/edit.html.erb
>        <%= form_with(model: @post, local: true ) do |f| %>
ごめんなさい指摘漏れです！
editでもnewでもフォームを設置してますが、ここは部分テンプレート化してあげるとよいです！

極力DRY原則を意識しましょう！

2020-11-22 12:48 UTC, sew-sou19 approved these changes
LGTMですー！

2020-11-22 12:53 UTC, merged