コメント投稿機能
keisukesaito7/tenkue-board-r009 pull request #13
Opened 2020-11-22 15:45 UTC by ikemomo

# 何か

- 投稿詳細ページでコメントができ、コメント一覧が表示される
- ブランクまたは140文字より多く入力した場合、エラーメッセージが表示される
- 自分のコメントにのみ編集・削除リンクが表示される
![comment_post](https://user-images.githubusercontent.com/61915228/99908122-16d40b80-2d24-11eb-89d2-8cb4a1c2dfcb.gif)

- 未ログイン時にはコメントフォームが表示されない
<img width="1323" alt="スクリーンショット 2020-11-23 0 31 07" src="https://user-images.githubusercontent.com/61915228/99908173-6c101d00-2d24-11eb-95f5-74dc0a54df3e.png">

- コメントの数がカウントされる,　コメント数0の時はカウントされない
- ログイン中であれば、コメントアイコンから詳細ページにアクセスできる
![comment_post_2](https://user-images.githubusercontent.com/61915228/99908196-9530ad80-2d24-11eb-9528-593169581dd4.gif)

-ログアウト中にコメントアイコンを押すと、ログインページに飛ばされる
![comment_post_3](https://user-images.githubusercontent.com/61915228/99908208-a4176000-2d24-11eb-8571-a3f118706bc3.gif)

# 追加・変更

- モデル
 - comment.rb
 - user.rb
 - post.rb

- マイグレーション
 - 20201118114937_create_comments.rb

- コントローラ
 - comments_controller.rb

- ビュー
 - posts/index.html.erb
 - posts/show.html.erb
 - comments/_index.html.erb
 - comments/_form.html.erb

- その他
 - route.rb
 - stylesheets/comments/_comments.scss
 - commentモデルを作成した時にできたファイル
 - rails db:migrate でできたファイル
 - commentコントローラを作成した時にできたファイル

2020-11-23 00:31 UTC, keisukesaito7 commented
複数ブランチのマージとコンフリクト解消、お疲れさまです！
LGTMです！

2020-11-23 03:28 UTC, aoi1019 commented
LGTMです！！

2020-11-23 05:37 UTC, sew-sou19 requested changes
.DS_Storeファイルはgitignoreに追加して、pushされないようにしておきましょうー！

また、他にもいくつか指摘させていただいたので、ご確認お願いします！

2020-11-23 05:37 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +  before_action :authenticate_user!
`before_action :authenticate_user!`が、likesコントローラーにも書かれているので、できれば処理をまとめたいところです！

今回の要件には入ってませんが、別の機能（例えばフォロー機能など）を実装する場合、そのコントローラーにも`before_action :authenticate_user!`を書くとなると、同じ記述が繰り返されてしまうので冗長です。

「ログインしてないとアクションを使えない」ための制限をする際のおすすめは、`before_action :authenticate_user!`を、applicationコントローラーに記述しておき、「ログインしなくても使えるアクション(post/indexなど)」は`skip_before_action`などで、ログイン認証をスキップするような記述にしてあげるとすっきりします！

2020-11-23 05:37 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +      redirect_to post_path(@post.id)
ここはリダイレクトよりrenderで記述してあげた方が良いです！
`redirect_to`だと、記述してた内容がクリアされてしまうのに対して、renderだと内容を保持したままページに戻れます。

```suggestion
      render 'posts/show'
```

2020-11-23 05:37 UTC, sew-sou19 commented on app/views/posts/show.html.erb
> +              <span><%= @comments.count if @post.comments.count > 0 %></span>
このチームはレベルが高いので、もう一歩踏み込んでレビューしますね！

`@comments.count if @post.comments.count`この記述ですが、ここもリファクタリングすることが可能です。
共通のメソッドを定義してあげて、それを利用することで保守性の高いコードにできます。

他で使用してる、共通化できる部分は
- app/views/posts/index.html.erbの`<%= post.comments.count if post.comments.count > 0 %>`
- app/views/likes/_like.html.erbの`<%= post.likes.count %>`

ヘルパーメソッドとしてメソッドを定義して、それを各ビューファイルで呼び出すとめちゃくちゃ良いです。
やり方が分からなければチームで話してみてください！

それでも回答が出なければこのままでもOKです！

2020-11-23 05:37 UTC, sew-sou19 commented on config/routes.rb
> +    resources :comments, only: [:new, :create, :edit, :update, :destroy]
ここは修正しなくてよいですが、原則として知っておいて欲しいのが「YAGNI原則」です！
意味はググってみてください！

メッセージとしては、このプルリクで実装しない部分の記述はしない方がベター、ということです！

2020-11-23 13:23 UTC, sew-sou19 requested changes
おー！ヘルパーメソッドの定義は素晴らしいです！

あともう少しだけ修正お願いします！

2020-11-23 13:23 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +  skip_before_action :authenticate_user!, only: :destroy
likes/destroyもログインしているユーザに限定するはずなので、ここの記述は不要ですー！
（と言うより`before_action :authenticate_user!, only: :create`が不要なことの指摘を漏らしてましたね、、、申し訳ないです）

2020-11-23 13:23 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
>    before_action :move_to_index, except: [:index, :show]
applicationコントローラで、`authenticate_user`を定義しているので、この記述は不要です！

2020-11-24 04:34 UTC, sew-sou19 approved these changes
LGTMです！さすがです

2020-11-24 06:54 UTC, merged