モデル単体テストコードの実装
keisukesaito7/tenkue-board-r009 pull request #14
Opened 2020-11-24 11:44 UTC by keisukesaito7

## 何か

* rspecの導入
* User/Post/Comment/Likeモデルの単体テストコードを実装

### 全モデルテスト結果

<a href="https://gyazo.com/a7625c2fd801bf3fbfdfd82ec13881d8"><img src="https://i.gyazo.com/a7625c2fd801bf3fbfdfd82ec13881d8.png" alt="Image from Gyazo" width="517"/></a>

## 追加・変更
* gem
  * Gemfile
  * Gemfile.lock
* rspec導入
  * .rspec
  * spec/rails_helper.rb
  * spec/spec_helper.rb
* spec/models
  * user_spec.rb
  * post_spec.rb
  * comment_spec.rb
  * like_spec.rb
* spec/factories
  * user.rb
  * post.rb
  * comment.rb
  * like.rb
* rspec install

2020-11-24 12:45 UTC, aoi1019 commented
とても確認しやすかったです！
LGTMです！

2020-11-24 15:08 UTC, ikemomo commented
コードレビューする側も勉強になりましたー!
LGTMです!

2020-11-27 08:38 UTC, sew-sou19 requested changes
おおー！素晴らしいですね！！
ほぼOKなんですが、一部だけ追加でテスト書いていただけるとより親切です！！

2020-11-27 08:38 UTC, sew-sou19 commented on spec/models/comment_spec.rb
> +    context '新規投稿ができるとき' do
文字制限などがある場合は、閾値の前後（今回で言えば140文字で登録できること）をテストしておくとより親切です！

2020-11-27 08:38 UTC, sew-sou19 commented on spec/models/user_spec.rb
> +      end
こちらも、「8文字以上32文字以下なら登録できる」のテストがあるとより親切です！

2020-11-27 09:11 UTC, keisukesaito7 commented on spec/models/comment_spec.rb
> +    context '新規投稿ができるとき' do
ありがとうございます！こちら、修正しました！

【追加したテスト】
commentが140文字であれば保存できる

【テスト結果 => OK】
<a href="https://gyazo.com/fc56103a296af576816b9b102570d8cf"><img src="https://i.gyazo.com/fc56103a296af576816b9b102570d8cf.png" alt="Image from Gyazo" width="498"/></a>

2020-11-27 09:12 UTC, keisukesaito7 commented on spec/models/user_spec.rb
> +      end
ありがとうございます！こちらも修正しました！

【追加したテスト】
・passwordが8文字であれば保存できる
・passwordが32文字であれば保存できる

【テスト結果 => OK】
<a href="https://gyazo.com/52f8534f1d0deec367477ce757f83480"><img src="https://i.gyazo.com/52f8534f1d0deec367477ce757f83480.png" alt="Image from Gyazo" width="511"/></a>

2020-11-27 09:13 UTC, keisukesaito7 commented
壮さん、レビューありがとうございます！
修正しましたので、改めてご確認をお願いします！

2020-11-28 03:44 UTC, sew-sou19 approved these changes
遅くなりました🙇‍♂️
LGTMですー！！

2020-11-28 04:24 UTC, keisukesaito7 commented
ありがとうございます！

2020-11-28 11:29 UTC, merged